apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: todoapi-route
spec:
  path: /
  to:
    kind: Service
    name: todoapi-service
  port:
    targetPort: 8081
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
