apiVersion: v1
kind: Namespace
metadata:
  name: todo-namespace
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: todoapp-channel
  namespace: todoapp-namespace
spec:
  type: Git
  pathname: https://github.com/melmanm/docker-todo-app.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: dev-clusters
  namespace: todoapp-namespace
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      todo: app
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: todoapp-subscription
  namespace: todoapp-namespace
  labels:
    app: todoapp-app
  annotations:
    apps.open-cluster-management.io/github-path: /kubernetes
spec:
  channel: todoapp-namespace/todoapp-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-clusters
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: todoapp-app
  namespace: todoapp-namespace
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - todoapp-app
