apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapi-deployment
  labels:
    app: todoapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapi
  template:
    metadata:
      labels:
        app: todoapi
    spec:
      containers:
        - name: todoapi
          image: melmanmankiewicz/todo_api:3.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: mongo-url
            - name: MONGO_LOGIN
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: mongo-user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: todoapi-service
spec:
  selector:
    app: todoapi
  ports:
    - name: 8081-tcp
      protocol: TCP
      port: 8081
      targetPort: 8080
