name: Docker Image CI

on:
  push:
    branches: [ master ]
jobs:
  init:
    outputs:
      datetag: ${{ steps.datetag.outputs.datetag }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."
      - name: Get current date tag
        id: datetag
        run: echo "::set-output name=datetag::$(date -u +'%Y-%m-%d_%H-%M-%S')"
  build:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          build-args: IMAGE_VERSION=${{ needs.init.outputs.datetag }}
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo_frontend:${{ needs.init.outputs.datetag }}
  deploy:
    needs: 
      - build
      - init
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.6.1"
    - name: Update Kubernetes resources
      run: |
       wget https://raw.githubusercontent.com/melmanm/docker-todo-app-kubernetes/master/kubernetes-acm/base/kustomization.yaml
       cat kustomization.yaml
       kustomize edit set image todo_frontend=${{ secrets.DOCKERHUB_USERNAME }}/todo_frontend:${{ needs.init.outputs.datetag }}
       cat kustomization.yaml
    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'kustomization.yaml'
        destination_repo: 'melmanm/docker-todo-app-kubernetes'
        destination_branch: 'master'
        destination_folder: 'kubernetes-acm/base'
        user_email: 'git@action.com'
        user_name: 'Git Action'
        commit_message: 'Automatic commit'

          
