name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  Init: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          repository: ${{ secrets.DOCKER_USERNAME }}/todo_frontend
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          path: frontend
          push: true
          tags: ${{ github.sha }}, latest
          
