name: Docker Image CI

on:
  push:
    branches: [ master ]
jobs:
  init:
    outputs:
      date: ${{ steps.date.outputs.date }}
      datetag: ${{ steps.datetag.outputs.datetag }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
      - name: Get current date tag
        id: datetag
        run: echo "::set-output name=datetag::$(date +'%Y%m%dT%H%M%S')"
  build:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo_frontend:${{ needs.init.outputs.datetag }}”
          
